logging:
  level:
    root: debug

server:
  port: 8080
  servlet:
    context-path: /api

base:
  bio: Hello!
  img:
    url: image.png

auth:
  key: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ

spring:
  jackson:
    deserialization:
      unwrap-root-value: true